# projects/Dockerfile
FROM golang:1.26-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o service ./cmd/auth/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/service .
COPY --from=builder /app/configs ./configs


CMD ["./service"]