// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: sources/sources.proto

package sources

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SourcesService_UploadSource_FullMethodName = "/sources.v1.SourcesService/UploadSource"
	SourcesService_GetSource_FullMethodName    = "/sources.v1.SourcesService/GetSource"
	SourcesService_ListSources_FullMethodName  = "/sources.v1.SourcesService/ListSources"
	SourcesService_DeleteSource_FullMethodName = "/sources.v1.SourcesService/DeleteSource"
	SourcesService_RetryJob_FullMethodName     = "/sources.v1.SourcesService/RetryJob"
)

// SourcesServiceClient is the client API for SourcesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Sources service
type SourcesServiceClient interface {
	// Upload source file
	UploadSource(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadSourceRequest, UploadSourceResponse], error)
	// Get source by id
	GetSource(ctx context.Context, in *GetSourceRequest, opts ...grpc.CallOption) (*SourceResponse, error)
	// List all sources in project
	ListSources(ctx context.Context, in *ListSourcesRequest, opts ...grpc.CallOption) (*ListSourcesResponse, error)
	// Delete source
	DeleteSource(ctx context.Context, in *DeleteSourceRequest, opts ...grpc.CallOption) (*DeleteSourceResponse, error)
	// Retry job if not started
	RetryJob(ctx context.Context, in *RetryJobRequest, opts ...grpc.CallOption) (*RetryJobResponse, error)
}

type sourcesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSourcesServiceClient(cc grpc.ClientConnInterface) SourcesServiceClient {
	return &sourcesServiceClient{cc}
}

func (c *sourcesServiceClient) UploadSource(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadSourceRequest, UploadSourceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SourcesService_ServiceDesc.Streams[0], SourcesService_UploadSource_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadSourceRequest, UploadSourceResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SourcesService_UploadSourceClient = grpc.ClientStreamingClient[UploadSourceRequest, UploadSourceResponse]

func (c *sourcesServiceClient) GetSource(ctx context.Context, in *GetSourceRequest, opts ...grpc.CallOption) (*SourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SourceResponse)
	err := c.cc.Invoke(ctx, SourcesService_GetSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourcesServiceClient) ListSources(ctx context.Context, in *ListSourcesRequest, opts ...grpc.CallOption) (*ListSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSourcesResponse)
	err := c.cc.Invoke(ctx, SourcesService_ListSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourcesServiceClient) DeleteSource(ctx context.Context, in *DeleteSourceRequest, opts ...grpc.CallOption) (*DeleteSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSourceResponse)
	err := c.cc.Invoke(ctx, SourcesService_DeleteSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourcesServiceClient) RetryJob(ctx context.Context, in *RetryJobRequest, opts ...grpc.CallOption) (*RetryJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryJobResponse)
	err := c.cc.Invoke(ctx, SourcesService_RetryJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourcesServiceServer is the server API for SourcesService service.
// All implementations must embed UnimplementedSourcesServiceServer
// for forward compatibility.
//
// Sources service
type SourcesServiceServer interface {
	// Upload source file
	UploadSource(grpc.ClientStreamingServer[UploadSourceRequest, UploadSourceResponse]) error
	// Get source by id
	GetSource(context.Context, *GetSourceRequest) (*SourceResponse, error)
	// List all sources in project
	ListSources(context.Context, *ListSourcesRequest) (*ListSourcesResponse, error)
	// Delete source
	DeleteSource(context.Context, *DeleteSourceRequest) (*DeleteSourceResponse, error)
	// Retry job if not started
	RetryJob(context.Context, *RetryJobRequest) (*RetryJobResponse, error)
	mustEmbedUnimplementedSourcesServiceServer()
}

// UnimplementedSourcesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSourcesServiceServer struct{}

func (UnimplementedSourcesServiceServer) UploadSource(grpc.ClientStreamingServer[UploadSourceRequest, UploadSourceResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadSource not implemented")
}
func (UnimplementedSourcesServiceServer) GetSource(context.Context, *GetSourceRequest) (*SourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSource not implemented")
}
func (UnimplementedSourcesServiceServer) ListSources(context.Context, *ListSourcesRequest) (*ListSourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSources not implemented")
}
func (UnimplementedSourcesServiceServer) DeleteSource(context.Context, *DeleteSourceRequest) (*DeleteSourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSource not implemented")
}
func (UnimplementedSourcesServiceServer) RetryJob(context.Context, *RetryJobRequest) (*RetryJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryJob not implemented")
}
func (UnimplementedSourcesServiceServer) mustEmbedUnimplementedSourcesServiceServer() {}
func (UnimplementedSourcesServiceServer) testEmbeddedByValue()                        {}

// UnsafeSourcesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourcesServiceServer will
// result in compilation errors.
type UnsafeSourcesServiceServer interface {
	mustEmbedUnimplementedSourcesServiceServer()
}

func RegisterSourcesServiceServer(s grpc.ServiceRegistrar, srv SourcesServiceServer) {
	// If the following call panics, it indicates UnimplementedSourcesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SourcesService_ServiceDesc, srv)
}

func _SourcesService_UploadSource_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SourcesServiceServer).UploadSource(&grpc.GenericServerStream[UploadSourceRequest, UploadSourceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SourcesService_UploadSourceServer = grpc.ClientStreamingServer[UploadSourceRequest, UploadSourceResponse]

func _SourcesService_GetSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourcesServiceServer).GetSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourcesService_GetSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourcesServiceServer).GetSource(ctx, req.(*GetSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourcesService_ListSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourcesServiceServer).ListSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourcesService_ListSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourcesServiceServer).ListSources(ctx, req.(*ListSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourcesService_DeleteSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourcesServiceServer).DeleteSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourcesService_DeleteSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourcesServiceServer).DeleteSource(ctx, req.(*DeleteSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourcesService_RetryJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourcesServiceServer).RetryJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourcesService_RetryJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourcesServiceServer).RetryJob(ctx, req.(*RetryJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SourcesService_ServiceDesc is the grpc.ServiceDesc for SourcesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SourcesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sources.v1.SourcesService",
	HandlerType: (*SourcesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSource",
			Handler:    _SourcesService_GetSource_Handler,
		},
		{
			MethodName: "ListSources",
			Handler:    _SourcesService_ListSources_Handler,
		},
		{
			MethodName: "DeleteSource",
			Handler:    _SourcesService_DeleteSource_Handler,
		},
		{
			MethodName: "RetryJob",
			Handler:    _SourcesService_RetryJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadSource",
			Handler:       _SourcesService_UploadSource_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "sources/sources.proto",
}
